@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
Container(webApp, "Веб приложение", "")
Container(messageBus, "Message Broker", "RabbitMQ")
ContainerDb(db, "База данных микросервиса", "PostgreSQL")
Container_Boundary(others, "Сервисы") {
    Component(handlers, "handlers", "", "Обрабатывает HTTP запросы")
    Component(messaging, "messaging", "", "Публикация и подписка на сообщения")
    Component(repo, "repository", "", "Работа с базой данных")
    Component(usecase, "use cases", "", "Бизнес-логика сервиса")
    Component(domain, "domain", "", "Модели и интерфейсы")
}

Rel(webApp, handlers, " ")
Rel(handlers, usecase, " ")
Rel(usecase, repo, " ")
Rel(usecase, messaging, " ")
Rel(usecase, domain, " ")
Rel(repo, domain, " ")
Rel(messaging, domain, " ")
Rel(repo, db, " ")
Rel(messaging, messageBus, " ")
@enduml
