@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(client, "Клиент", "Конечный пользователь системы умного дома")
System_Ext(device, "Датчики")

System_Boundary(smartHomeSystem, "Управление умным домом"){
    Container(warm, "Управление отоплением", "Go Service", "Ответственен за: бизнес-правила управления отоплением, температурные режимы, расписание и сценарии, проверка прав доступа.")
    Container(light, "Управление освещением", "", "Ответственен за: бизнес-правила управления освещением, сценарии включение/выключение, проверка прав на управление освещением.")
    Container(gate, "Управление воротами", "Go Service", "Ответственен за: правила открытия/закрытия, проверка прав доступа.")
    Container(watch, "Управление наблюдением", "Go Service", "Ответственен за: контроль доступа к камерам, бизнес-правила наблюдения")
    Container(deviceIntegration, "Интеграция устройств", "Go Service", "Инфраструктурный сервис для взаимодействия с физическими устройствами. Ответственен за: подключение и регистрация устройств, взаимодействие с датчиками по протоколам, получение реального состояния устройств")
    Container(userManagement, "Управление пользователями", "Go Service", "Управление учетными записями пользователей и их правами доступа. Ответственен за: хранение пользователей, роли и права, аутентификация, принадлежность пользователя к дому.")
    Container(webApp, "Веб приложение", "", "Альтернативный пользовательский интерфейс для доступа к системе через браузер.")
    Container(mobileApp, "Мобильное приложение", "", "Пользовательский интерфейс для управления умным домом с мобильных устройств.")
    Container(gateway, "API Gateway", "Go Service", "Единая точка входа в систему для клиентских приложений. Ответственен за: маршрутизацию, базовую авторизацию, агрегацию данных.")
    Container(home, "Управление структурой дома", "Go Service", "Описание логической структуры умного дома. Ответственен за: дома, комнаты, зоны.")
    Container(messageBus, "Message Broker", "RabbitMQ", "Асинхронная доставка команд и событий")
    Container(telemetry, "Телеметрия и история", "Kotlin Vertx Service", "Хранение и предоставление исторических и аналитических данных. Ответственен за: хранение истории состояний и измерений, предоставление данных для графиков и аналитики, мониторинг")
}

Rel(client, webApp, "Использует")
Rel(client, mobileApp, "Использует")
Rel(mobileApp, gateway, " ")
Rel(webApp, gateway, " ")
Rel(gateway, warm, " ")
Rel(gateway, light, " ")
Rel(gateway, gate, " ")
Rel(gateway, watch, " ")
Rel(gateway, deviceIntegration, " ")
Rel(gateway, userManagement, " ")
Rel(gateway, home, " ")
Rel(gateway, telemetry, " ")
Rel(deviceIntegration, device, "Удаляет/добавляет датчики. \n Управляет состоянием.")
Rel(deviceIntegration, messageBus, "Публикует события")
Rel(messageBus, deviceIntegration, "Доставляет команды")

Rel(telemetry, messageBus, "Читает событие")
Rel(warm, messageBus, "Отправляет команды")
Rel(light, messageBus, "Отправляет команды")
Rel(gate, messageBus, "Отправляет команды")
Rel(watch, messageBus, "Отправляет команды")

@enduml