@startuml Warmhouse_C4_Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Warmhouse

Person(user, "Пользователь")
Person(master, "Мастер")

System(warmhouse, "Warmhouse")
System_Ext(temperatureService, "Температура")

Rel(user, warmhouse, "Запрашивает данные по датчикам")
Rel(master, warmhouse, "Создает или удаляет датчик")
Rel(warmhouse, temperatureService, "Запрашивает данные по температуре")
@enduml
